// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEslUsBv8uOyXIXqsbehPDqgHx2PCUYIY',
    appId: '1:416541870242:web:1e776958241f3184e76ffb',
    messagingSenderId: '416541870242',
    projectId: 'esptest1-edcd8',
    authDomain: 'esptest1-edcd8.firebaseapp.com',
    databaseURL: 'https://esptest1-edcd8-default-rtdb.firebaseio.com',
    storageBucket: 'esptest1-edcd8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEslUsBv8uOyXIXqsbehPDqgHx2PCUYIY',
    appId: '1:416541870242:web:1e776958241f3184e76ffb',
    messagingSenderId: '416541870242',
    projectId: 'esptest1-edcd8',
    authDomain: 'esptest1-edcd8.firebaseapp.com',
    databaseURL: 'https://esptest1-edcd8-default-rtdb.firebaseio.com',
    storageBucket: 'esptest1-edcd8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlhkl74mHfqO-cQnJ5w712_2d3vOIeWoQ',
    appId: '1:416541870242:ios:219d5d57583aab87e76ffb',
    messagingSenderId: '416541870242',
    projectId: 'esptest1-edcd8',
    databaseURL: 'https://esptest1-edcd8-default-rtdb.firebaseio.com',
    storageBucket: 'esptest1-edcd8.firebasestorage.app',
    iosBundleId: 'com.example.espiot',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlhkl74mHfqO-cQnJ5w712_2d3vOIeWoQ',
    appId: '1:416541870242:ios:219d5d57583aab87e76ffb',
    messagingSenderId: '416541870242',
    projectId: 'esptest1-edcd8',
    databaseURL: 'https://esptest1-edcd8-default-rtdb.firebaseio.com',
    storageBucket: 'esptest1-edcd8.firebasestorage.app',
    iosBundleId: 'com.example.espiot',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-1NAEfP8Br1B3nBexJ_LK82URzMoZXvU',
    appId: '1:416541870242:android:691462a2f33122cce76ffb',
    messagingSenderId: '416541870242',
    projectId: 'esptest1-edcd8',
    databaseURL: 'https://esptest1-edcd8-default-rtdb.firebaseio.com',
    storageBucket: 'esptest1-edcd8.firebasestorage.app',
  );

}